### ISSUE TITLE
(0.1) Uvicorn running on http://0.0.0.0:8000 

### ISSUE THREAD

**Issue by stewartugelow** [arcee-ai/fastmlx#12]
Uvicorn is running on http://0.0.0.0:8000 instead of http://localhost:8000

Perplexity tells me this is a potential security risk?

`Running a server on `0.0.0.0` makes it accessible from any IP address, which can be a security risk if the server is exposed to the public internet. Ensure that you have appropriate security measures in place, such as firewalls, authentication, and encryption, to protect your server.
`

**Comment by Blaizzy** [comment]
You can customize the host by passing it on start:

```shell
fastmlx --host 127.0. 0.1 
```
or
```shell
fastmlx --host localhost
```

**Comment by stewartugelow** [comment]
Sorry, what I meant to say was: in the original version, it ran on localhost. In the new version, it runs on 0.0.0.0. I wanted to flag it for you in case this wasn't an intentional change.
