### ISSUE TITLE
Cross origin support

### ISSUE THREAD

**Issue by digicali** [arcee-ai/fastmlx#2]
Will be sweet to add Cross origin support to allows an IP address to be used or a secure domain

Like LMStudio or Jan Server. Allows inference servers to be used by developers with a fixed IP address or a secure domain. 

<img width="736" alt="Screenshot 2024-07-09 at 15 35 35" src="https://github.com/Blaizzy/fastmlx/assets/36820800/9d5e797b-3814-47dc-b96e-117b54c06c98">

**Comment by Blaizzy** [comment]
Hey @digicali

Thanks for bringing this up!

I have looked into it and proposed this PR #4 

Can you check and let me know if this solves your issue?

**Comment by Blaizzy** [comment]
Example: 

```shell
fastmlx --allowed-origins http://localhost:3000 http://127.0.0.1:3000
```

**Comment by digicali** [comment]
Should be good enough!

**Comment by Blaizzy** [comment]
Perfect!

I will merge it and release it 🚀
