### ISSUE TITLE
ReadMe Broken Docs Link

### ISSUE THREAD

**Issue by larson-carter** [arcee-ai/fastmlx#33]
In the readme of the repo the documentation link throws 404 error. 

Link that is attached: https://blaizzy.github.io/fastmlx

@Blaizzy

**Comment by Blaizzy** [comment]
Working on it

Here is the PR:
#19

**Comment by Blaizzy** [comment]
Hopefully will merge it soon

**Comment by Blaizzy** [comment]
#19 is merged and the docs are available!
